# Generated by Django 4.2.2 on 2024-02-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_attendance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DayLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('Local_church', models.CharField(choices=[('SB', 'South B'), ('KIB', 'Kiambiu'), ('KTE', 'Kitengela'), ('WAD', 'Waudo'), ('EAS', 'Eastleigh'), ('UMJ', 'Umoja'), ('MUT', 'Muthaiga'), ('RU', 'Runda'), ('KAR', 'Kariokor')], max_length=100)),
                ('category', models.CharField(choices=[('L', 'Leaner'), ('T', 'Teacher'), ('P', 'Leader')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(choices=[('BK1', 'Book One'), ('BK2', 'Book Two')], max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=100)),
                ('levels', models.CharField(choices=[('BK1', 'Book One'), ('BK2', 'Book Two')], max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('learner', models.ManyToManyField(through='register.DayLesson', to='register.attendance')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('N', 'Normal'), ('O', 'Online'), ('SB', 'Schoolbased'), ('SP', 'Special')], max_length=100)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='daylesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.lesson'),
        ),
        migrations.CreateModel(
            name='ClassDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.lessontopic')),
                ('students', models.ManyToManyField(through='register.Attendance', to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='classday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.classday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student'),
        ),
    ]
