# Generated by Django 4.2.2 on 2024-02-23 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_attendance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=100)),
                ('levels', models.CharField(choices=[('BK1', 'Book One'), ('BK2', 'Book Two')], max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('mode', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Online', 'Online'), ('SchoolBased', 'Schoolbased'), ('Special', 'Special')], max_length=100, null=True)),
                ('is_taught', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('Local_church', models.CharField(choices=[('South B', 'South B'), ('Kiambiu', 'Kiambiu'), ('Kitengela', 'Kitengela'), ('Waudo', 'Waudo'), ('Eastleigh', 'Eastleigh'), ('Umoja', 'Umoja'), ('Muthaiga', 'Muthaiga'), ('Runda', 'Runda'), ('Kariokor', 'Kariokor')], max_length=100)),
                ('category', models.CharField(choices=[('L', 'Leaner'), ('T', 'Teacher'), ('P', 'Leader')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(blank=True, choices=[('BK1', 'Book One'), ('BK2', 'Book Two')], max_length=100, null=True)),
                ('mode', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Online', 'Online'), ('SchoolBased', 'Schoolbased'), ('Special', 'Special')], max_length=100, null=True)),
                ('att_count', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.lessontopic')),
            ],
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='register.person'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.lessontopic')),
                ('students', models.ManyToManyField(through='register.Attendance', to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='classday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.classday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student'),
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.onlinelesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classday', 'students')},
        ),
    ]
