# Generated by Django 4.2.2 on 2024-02-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classday',
            old_name='date',
            new_name='date_created',
        ),
    ]
