# Generated by Django 4.2.2 on 2024-02-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontopic',
            old_name='date',
            new_name='Taught_on_date',
        ),
    ]
