# Generated by Django 4.2.2 on 2024-02-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_date_lessontopic_taught_on_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontopic',
            old_name='Taught_on_date',
            new_name='taught_on_date',
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
