# Generated by Django 4.2.2 on 2024-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_lessonsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsummary',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
