# Generated by Django 4.2.2 on 2024-03-07 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0007_onlinelearner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelearner',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person'),
        ),
        migrations.AlterUniqueTogether(
            name='onlinelearner',
            unique_together={('user', 'student')},
        ),
    ]
