# Generated by Django 4.2.2 on 2024-03-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_onlinelearner_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinelearner',
            old_name='student',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='onlinelearner',
            unique_together=set(),
        ),
    ]
