# Generated by Django 4.2.2 on 2024-03-07 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0009_rename_student_onlinelearner_person_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlinelearner',
            unique_together={('user', 'person')},
        ),
    ]
