# Generated by Django 4.2.2 on 2024-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_onlinelearner_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
