# Generated by Django 4.2.2 on 2024-03-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_onlinelearner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='students',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classday', 'person')},
        ),
    ]
