# Generated by Django 4.2.2 on 2024-03-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_rename_students_attendance_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='person',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classday', 'student')},
        ),
    ]
