# Generated by Django 4.2.2 on 2024-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_rename_person_attendance_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
