# Generated by Django 4.2.2 on 2024-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_remove_notice_content_notice_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontopic',
            name='date_taught',
            field=models.DateField(blank=True, null=True),
        ),
    ]
