# Generated by Django 4.2.2 on 2024-03-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_lessontopic_date_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('L', 'Learner'), ('T', 'Teacher'), ('P', 'Leader'), ('M', 'Member')], max_length=100),
        ),
    ]
