# Generated by Django 4.2.2 on 2024-03-15 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0017_alter_person_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnlineLearner',
            new_name='OnlinePerson',
        ),
    ]
