# Generated by Django 4.2.2 on 2024-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_rename_onlinelearner_onlineperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_percent',
            field=models.IntegerField(default=100),
        ),
    ]
