# Generated by Django 4.2.2 on 2024-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_person_date_created_student_attendance_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance_percent',
            field=models.IntegerField(default=1),
        ),
    ]
