# Generated by Django 4.2.2 on 2024-03-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0020_alter_student_attendance_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineperson',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.person'),
        ),
        migrations.AlterField(
            model_name='onlineperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
